spring:
  application:
    name: video-to-testcase
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB


ai:
  openai:
    api-key: YOUR_API_KEY
    model: gemini-2.5-flash
  gemini:
    api-key: YOUR_API_KEY
    model: gemini-2.5-flash
